config/routes.rb
  Rainforest::Application.routes.draw do
  root :to => "products#index"

  get "reviews/show"
  get "reviews/new"
  get "reviews/edit"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "users/new"
  get "users/create"
  
  resources :users, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :products do
    resources :reviews, :except => [:index]
  end

  
  end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  has_many :users, :through => :reviews

  validates :description, :name, :presence => true
  validates :price_in_cents, :numericality => {:only_integer => true}


  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :comment, :presence => true
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password #automatically creates accessible :password, :password_confirmation
  has_many :reviews
  has_many :products, :through => :reviews
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to_new_session_path
    end
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] # ||= (or equals) assigns item if item currently nil
  end

  helper_method :current_user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])

    if current_user
      @review = Review.new
    end
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to product_path
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :load_product
  before_filter :ensure_logged_in, :only => [:edit, :create, :show, :update, :destroy]

  def show
  @review = Review.find(params[:id])
  end

  def create


    #params.require(:review).permit(:comment, :product_id)
    #@review = @product.reviews.build(review_params)
    @review = Review.new( 
      :comment => params[:review][:comment],
      :product_id => @product.id,
      :user_id => current_user.id
      )

    #@review.user_id = current_user.id
  respond_to do |format|
      if @review.save
        format.html { redirect_to product_path(@product.id), notice: 'Review added' }
        format.js {} # This will look for /views/reviews/create.js.erb
        #redirect_to product_path(@product), notice: 'Review created successfully'
      else
        #render :action => :show
        format.html { render "products/show", notice: 'There was an error.'}
        format.js {} # This will look for /views/reviews/create.js.erb
      end
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@product)
  end

  def new
  @review = Review.new
  end

  def update
    @review = Review.find(params[:id])

    if @review.update_attributes(review_params)
      redirect_to product_review_path
    else
      render :edit
    end
  end


  def edit
    @review = Review.find(params[:id])
  end

  private
  def review_params
    params.require(:review).permit(:comment, :product_id)
  end

  def load_product
    @product = Product.find(params[:product_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, :notice => "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to products_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  private
  def  user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <h1>Welcome to the Rainforest</h2>
  <% if flash[:notice] %>
  <p id="notice"><%= flash[:notice] %></p>
<% end %>
<% if flash[:alert] %>
  <p id="alert"><%= flash[:alert] %></p>
<% end %>

<%= yield %>

  <p class="userinfo">
    <% if current_user %>
      Signed in as <%= current_user.email %>, <%= link_to "Log out", session_path("current"), :method => :delete %>

    <% else %>
      <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
      <% end %>
    </p>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>

  <% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

    <ul>
      <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
<% end %>
    

<%= form_for(@product) do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_cents %><br />
    <%= f.number_field :price_in_cents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_review_form_errors.html.erb
<% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

app/views/products/_reviews.html.erb
<% @product.reviews.each do |review| %>
  <div class="review">
    <p>
        <%= review.comment %>
          <%= link_to "modify", "#{product_path}/reviews/#{review.id}" %>
        <br>
        <% if review.user != nil %>
          <em> By <%= review.user.email %></em>
          <em>Added on:</em> <%= review.created_at %>
        <% end %>
    </p>
  </div>
<% end %>

app/views/products/edit.html.erb
<h2>Modifying <%= @product.name %></h2>

<%= render "form" %>

<%= link_to "Back", @product %>

app/views/products/index.html.erb
<% @products.each do |product| %>

<ul>
  <li><%= "Name: " %><%= link_to product[:name], "/products/#{product[:id]}" %></li>
  <li><%= "Price: $#{product.formatted_price}"%></li>
</ul>

<% end %>

<%= link_to "Add new product", "/products/new" %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h2><%= @product.name %></h2>

<%= link_to "Back to Products", products_url %> | <%= link_to "Edit Product", edit_product_path(@product) %> | <%= link_to "Delete Product", @product, :confirm => "Are you sure you want to delete this item?", :method => :delete %>

<ul>
  <li><%= "Name: #{@product[:name]}" %></li> 
  <li><%= "Price #{@product.formatted_price}"%></li>
  <li><%= "Description: #{@product[:description]}" %></li>
</ul>

<% if current_user %>

  <h3>Reviews for <%= @product.name %></h3>

  <div id="review=list">
    <%= render partial: "products/reviews" %>
  </div>

  <h4>New Review</h4>

  <%= form_for([@product, @review]) do |f| %>
    <div id="review-form-errors">
      <%= render :partial => "/products/review_form_errors" %>
    </div>
    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to view reviews or add your own.</p>
<% end %>

app/views/reviews/_edit_form.html.erb
<%= form_for([@product, @review]) do |f| %>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>

  <% end %>

app/views/reviews/create.js.erb
// alert("I'm responding to your request!");
$("#review-list").html("<%= escape_javascript(render(partial: '/products/reviews')) %>");

app/views/reviews/edit.html.erb
<h2>Edit Review</h2>

<%= link_to "Back to Product", product_path(@product) %>
<%= render "edit_form" %>
  

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>

<%= link_to "Back to Product", product_path(@product) %> | <%= link_to "Delete Review", @reviews, :confirm => "Are you sure you want to delete this review?", :method => :delete %><p>


<p>Review for: <%= @product.name %></p>

    <div class="review">
      <p> 
          <br>
            <%= render "edit_form" %>
            <em> Review by <%= @review.user.email %></em>
            <em>Added on:</em> <%= @review.created_at %>

      </p>
    </div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<p>Find me in app/views/users/new.html.erb</p>

<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>